parameters:
  biz: 
    database:
      name: "%database_name%"
      user: "%database_user%"
      password: "%database_password%"
      host: "%database_host%"
      port: "%database_port%"
      driver: pdo_mysql
      charset: UTF8