# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    app.current_user.class: AppBundle\Security\CurrentUser
    app.csrf.token_id.default: app 
    app.csrf.token_form_name: _csrf_token
    
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    biz:
        class: Biz\BizKernel
        arguments: ["%biz%", "@service_container"]

    app_asset_helper.twig_extension:
        class: AppBundle\Twig\AssetHelperExtension
        arguments:    ['@service_container']
        public: false
        tags:
            - { name: twig.extension }

    twig.app_extension:
        class: AppBundle\Twig\AppExtensions
        arguments:    ['@service_container']
        tags:
            - { name: twig.extension }

    twig.html_extension:
        class: AppBundle\Twig\HtmlExtension
        tags:
            - { name: twig.extension }

    app.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: ["@biz"]
        
    app.csrf_token_validate_listener:
         class: AppBundle\Listener\CsrfTokenValidateListener
         arguments:    ['@service_container']
         tags:
             - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority:255 }
